#!/usr/bin/php
<?php

use RemoteTinker\Config;
use RemoteTinker\RunOnRemote;
use RemoteTinker\SetConfig;
use function Laravel\Prompts\error;
use function Laravel\Prompts\info;

require $_composer_autoload_path ?? (__DIR__ . '/vendor/autoload.php');

$args = array_slice($argv, 1);
$flags = array_values(array_filter($args, fn($a) => str_starts_with($a, '-')));
$command = null;

foreach ($args as $a) {
    if (!str_starts_with($a, '-')) {
        $command = $a;
        break;
    }
}

if ($command === null && (in_array('--help', $flags, true) || in_array('-h', $flags, true))) {
    $command = 'help';
}

switch ($command) {

    case null:

        (new RunOnRemote())($flags);

        break;

    case 'setup':
    case 'config':

        (new  SetConfig)->setup();

        break;
    case 'help':

        info("Remote tinker:");
        info("Run a local file in Tinker on a remote server");
        info("");
        info("Commands:");
        info("  (no command)  Run the interactive runner");
        info("  setup         Configure remote servers");
        info("  help          Display this message");
        info("");
        info("Flags (with no command):");
        info("  --return-files     Pull output files back from REMOTE_TINKER_OUTPUT_DIR after the run");
        info("  --no-return-files  Skip the file-pull prompt entirely");

        break;

    default:
        error('Invalid command. Try --help');

        return 1;


}
